safe:        true
baseurl:    /
url:        http://localhost:4000

destination: ./_site

future:      false
lsi:         false
permalink:   /:year-:month-:day/:title.html

collections:
  guide:
    output: true
