safe:        true
baseurl:    /
url: http://localhost:4000

destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    redcarpet
permalink:   /:year-:month-:day/:title.html

